Se hace maqueta inicial
kunder-lab/kunder-exam-frontend pull request #1
Opened 2018-02-28 14:25 UTC by dariokunder

2018-02-28 14:38 UTC, sebalagos90 requested changes

2018-02-28 14:38 UTC, sebalagos90 commented on src/components/home/home.ts
> +import { Component } from '@angular/core';
El nombre de los componentes deberían ser de la siguiente forma:
`nombre-componente-subseccion.component.ts`.
Favor de corregir esto y cambiar las referencias correspondientes.

2018-02-28 14:38 UTC, sebalagos90 commented on src/components/home/home.scss
> +        // background-color: map-get($colors, primary);
Please remove commented code.

2018-03-01 18:34 UTC, sebalagos90 reviewed
Además, favor de eliminar imágenes de la tipografía. No son de utilidad

2018-03-01 18:34 UTC, sebalagos90 commented on package.json
> +{
[S:0] Favor de cambiar los datos de ionic por los de kunder.

2018-03-01 21:25 UTC, gabrielagb requested changes
En general los nombres de las clases deberían ser con minúscula y guiones. Eso es el estándar para no confundir clases de css con clases de componentes o cosas de frontend. En este caso lo podemos dejar pasar.

2018-03-01 21:25 UTC, gabrielagb commented on src/components/home/home.html
> +        <span class="telecom">telecom</span>
El logo debería ir como background-image en un div. Esto se hace así para que sea mantenible, en cualquier momento el cliente podría cambiar su logo y querer poner uno nuevo, y eso se debería manejar por css sin intervenir el html.

2018-03-01 21:25 UTC, gabrielagb commented on src/components/home/home.html
> +          <img src="assets/imgs/i-menu.svg" class="menuIcon">
Lo mismo. Debería ser background-image de menuButton.

2018-03-01 21:25 UTC, gabrielagb commented on src/components/home/home.html
> +      </button>
👍

2018-03-01 21:25 UTC, gabrielagb commented on src/components/home/home.html
> +  <div class="smartphoneLogo">
Esta clase debería llamarse "header" o algo más abstracto. Se puede dar el caso en que ya no sea un smartphone la imagen y la clase dejaría de tener relación.

2018-03-01 21:25 UTC, gabrielagb commented on src/components/home/home.html
> +      <button class="buttonsHome buttonPlan borderLeft">
No es necesario hacer una clase específica para los bordes. El html y sus clases deben estar estructurados de manera de que cualquier cambio estético sea realizable sólo mediante css. En este caso no sería así ya que tendrías que intervenir el html y borrar la clase para quitárselo.

El borde lo puedes poner agregando una pseudoclase al elemento para seleccionarlo.

2018-03-01 21:25 UTC, gabrielagb commented on src/components/home/home.html
> +      <a class="shuffleLeft">Consultas</a>
En el diseño estos ítems iban al revés. Consultas | Sucursales.

2018-03-01 21:25 UTC, gabrielagb commented on src/components/home/home.html
> +<ion-footer class="customFooter">
No recomiendo el nombre custom footer para una clase, ya que cualquier footer en verdad podría ser custom. Podría ser "information-footer".

2018-03-01 21:25 UTC, gabrielagb commented on src/components/home/home.scss
> +            height: calc(100vh - 32.9vh - 76px - 56px);
👍

2018-03-01 21:25 UTC, gabrielagb commented on src/components/home/home.scss
> +
Podrías hacerlo más o menos así (no exactamente):

.buttonsHome{
...atributos...
&:nth-child(1){border-top: solid 2px rgb(233, 233, 233);}
&:nth-child(3) {border-top: solid 2px rgb(233, 233, 233);border-left: solid 2px rgb(233, 233, 233);}
}

2018-03-01 21:56 UTC, gabrielagb requested changes

2018-03-01 21:56 UTC, gabrielagb commented on src/components/home/home.html
> +<ion-footer class="information-footer">
Ups. En este caso habría que seguir el estándar de nombres usado en este proyecto, entonces sería informationFooter.

2018-03-01 21:56 UTC, gabrielagb commented on src/components/home/home.scss
> +                $buttonBorderColor : rgb(233, 233, 233);
La declaración de variables debería ir al inicio del documento.

2018-03-01 21:56 UTC, gabrielagb commented on src/theme/nav.scss
> +    background-image: url('../assets/imgs/kunder-logo.svg');
Esto se podría abreviar (sólo recomendación)

2018-03-01 22:30 UTC, gabrielagb approved these changes

2018-03-02 13:14 UTC, sebalagos90 approved these changes

2018-03-02 13:29 UTC, merged